#!/usr/bin/env python3
"""bundle.py – Inline web assets into a self-contained HTML file and emit a
C++ constexpr string_view header for embedding in the msmap binary.

Usage:
    python3 bundle.py <template.html> <output.h> [VAR_NAME]

VAR_NAME defaults to kIndexHtml.  All asset paths are resolved relative to
the directory that contains template.html.
"""

import os
import sys

# Map placeholder tokens in index.html to asset paths (relative to web/).
_PLACEHOLDERS = [
    ('{{LEAFLET_CSS}}',             'vendor/leaflet.min.css'),
    ('{{MARKERCLUSTER_CSS}}',       'vendor/MarkerCluster.css'),
    ('{{MARKERCLUSTER_DEFAULT_CSS}}', 'vendor/MarkerCluster.Default.css'),
    ('{{APP_CSS}}',                 'app.css'),
    ('{{LEAFLET_JS}}',              'vendor/leaflet.min.js'),
    ('{{MARKERCLUSTER_JS}}',        'vendor/leaflet.markercluster.js'),
    ('{{APP_JS}}',                  'app.js'),
]

# Delimiter chosen to be absent from any HTML/CSS/JS content.
_RAW_DELIM = 'MSMAP_HTML_END'


def _read(path: str) -> str:
    with open(path, encoding='utf-8') as fh:
        return fh.read()


def bundle(template_path: str) -> str:
    """Return the fully-inlined HTML string."""
    base = os.path.dirname(os.path.abspath(template_path))
    html = _read(template_path)
    for token, rel in _PLACEHOLDERS:
        html = html.replace(token, _read(os.path.join(base, rel)))
    return html


def emit_header(html: str, var_name: str) -> str:
    """Return a C++ header containing the HTML as a constexpr string_view.

    The bundled HTML typically exceeds 65 536 characters, which triggers
    -Woverlength-strings under -Wpedantic.  We suppress it with a pragma
    that is respected by both clang and clang-tidy.
    """
    # Verify the delimiter is absent – if it appears we'd produce invalid C++.
    if _RAW_DELIM in html:
        raise ValueError(
            f'Raw-string delimiter "{_RAW_DELIM}" found in bundled HTML. '
            'Choose a different _RAW_DELIM.'
        )

    return (
        '// AUTO-GENERATED by web/bundle.py — do not edit manually\n'
        '#pragma once\n'
        '#include <string_view>\n'
        'namespace msmap::web {\n'
        '// The bundled HTML exceeds the C++ standard minimum (65 536 chars).\n'
        '// Suppress the Clang/GCC pedantic diagnostic for this one variable.\n'
        '#pragma clang diagnostic push\n'
        '#pragma clang diagnostic ignored "-Woverlength-strings"\n'
        f'constexpr std::string_view {var_name}{{R"{_RAW_DELIM}(\n'
        f'{html}'
        f'){_RAW_DELIM}"}};\n'
        '#pragma clang diagnostic pop\n'
        '} // namespace msmap::web\n'
    )


def main() -> None:
    if len(sys.argv) < 3:
        print(f'Usage: {sys.argv[0]} <template.html> <output.h> [VAR_NAME]',
              file=sys.stderr)
        sys.exit(1)

    template = sys.argv[1]
    output   = sys.argv[2]
    var_name = sys.argv[3] if len(sys.argv) > 3 else 'kIndexHtml'

    html   = bundle(template)
    header = emit_header(html, var_name)

    os.makedirs(os.path.dirname(os.path.abspath(output)), exist_ok=True)
    with open(output, 'w', encoding='utf-8') as fh:
        fh.write(header)

    size_kb = len(html.encode('utf-8')) / 1024
    print(f'bundled {size_kb:.1f} KB → {output}', file=sys.stderr)


if __name__ == '__main__':
    main()
